<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * corp-api
 *
 * Corp API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kletser@maximalabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteReservation
     *
     * Delete a reservation.
     *
     */
    public function testDeleteReservation()
    {
    }

    /**
     * Test case for getReservation
     *
     * Get a reservation.
     *
     */
    public function testGetReservation()
    {
    }

    /**
     * Test case for makeReservation
     *
     * Make a reservation.
     *
     */
    public function testMakeReservation()
    {
    }

    /**
     * Test case for meetingRoomItem
     *
     * Get meeting rooms by its id.
     *
     */
    public function testMeetingRoomItem()
    {
    }

    /**
     * Test case for meetingRoomList
     *
     * Get meeting rooms filtered by provided parameters.
     *
     */
    public function testMeetingRoomList()
    {
    }

    /**
     * Test case for reservations
     *
     * Get reservations of meeting rooms filtered by provided parameters.
     *
     */
    public function testReservations()
    {
    }

    /**
     * Test case for updateReservation
     *
     * Update a reservation.
     *
     */
    public function testUpdateReservation()
    {
    }
}
